/* Módulo independente: não altera a reserva rápida existente. */
const STORE='senac-gestao-salas';
const HOURS=['08:00 - 10:00','10:15 - 12:15','13:30 - 15:30','15:45 - 17:45','19:00 - 21:00','21:15 - 23:00'];
const initial={current:'ana',users:[{id:'ana',name:'Ana Martins',role:'admin',active:true,areas:['*']},{id:'carlos',name:'Carlos Souza',role:'manager',active:true,areas:['Bloco B']},{id:'marina',name:'Marina Lima',role:'teacher',active:true,areas:[]},{id:'joao',name:'João Silva',role:'teacher',active:false,areas:[]}],rooms:[{id:'101',name:'Sala 101',floor:'1º andar - Bloco A',capacity:35,description:'Sala de aula',resources:['Projetor','Quadro','Ar-condicionado']},{id:'202',name:'Sala 202',floor:'2º andar - Bloco A',capacity:28,description:'Sala colaborativa',resources:['TV','Quadro']},{id:'lab',name:'Lab. Informática',floor:'1º andar - Bloco B',capacity:25,description:'Laboratório',resources:['Computadores','Projetor']},{id:'aud',name:'Auditório',floor:'Térreo - Bloco B',capacity:120,description:'Eventos',resources:['Som','Projetor','Microfones']}],requests:[]};
const get=()=>JSON.parse(localStorage.getItem(STORE)||JSON.stringify(initial)); const put=x=>localStorage.setItem(STORE,JSON.stringify(x)); const id=()=>Date.now().toString(36)+Math.random().toString(36).slice(2); const day=()=>new Date().toISOString().slice(0,10); const br=x=>new Date(x+'T12:00').toLocaleDateString('pt-BR');
const room=(d,x)=>d.rooms.find(r=>r.id===x), me=d=>d.users.find(u=>u.id===d.current), sector=r=>r.floor.split(' - ')[1]||r.floor;
const canManage=(d,x)=>me(d).role==='admin'||(me(d).role==='manager'&&me(d).areas.includes(sector(room(d,x.room))));
const status=x=>({pending:'Aguardando aprovação',approved:'Aprovada',rejected:'Recusada',cancelled:'Cancelada'})[x];
function dates(start,repeat,until){let out=[],p=new Date(start+'T12:00'),end=new Date((until||start)+'T12:00'),week=p.getDay();while(p<=end){if(repeat==='one'||(repeat==='daily'&&p.getDay()>0&&p.getDay()<6)||(repeat==='weekly'&&p.getDay()===week))out.push(p.toISOString().slice(0,10));p.setDate(p.getDate()+1)}return out}
function esc(v){let e=document.createElement('span');e.textContent=v??'';return e.innerHTML} function msg(v){alert(v)}
function management(){if(!document.getElementById('requestForm'))return;let d=get(); const profile=document.getElementById('profile');profile.innerHTML=d.users.filter(u=>u.active).map(u=>`<option value="${u.id}" ${u.id===d.current?'selected':''}>${u.name} · ${u.role}</option>`).join('');profile.onchange=()=>{d=get();d.current=profile.value;put(d);location.reload()};document.getElementById('who').textContent=me(d).name+' · '+me(d).role;
 document.querySelectorAll('.manager').forEach(x=>x.classList.toggle('hidden',me(d).role==='teacher'));document.querySelectorAll('.admin').forEach(x=>x.classList.toggle('hidden',me(d).role!=='admin'));
 const roomSelect=document.getElementById('room');roomSelect.innerHTML=d.rooms.map(r=>`<option value="${r.id}">${esc(r.name)} · ${esc(r.floor)}</option>`).join('');time.innerHTML=HOURS.map(x=>`<option>${x}</option>`).join('');start.value=day();calDate.value=day();
 function roomDetail(){let r=room(get(),roomSelect.value);roomInfo.textContent=`${r.capacity} lugares · ${r.resources.join(', ')}`}roomSelect.onchange=roomDetail;roomDetail();repeat.onchange=()=>untilBox.classList.toggle('hidden',repeat.value==='one');
 document.querySelectorAll('[data-v]').forEach(b=>b.onclick=()=>{document.querySelectorAll('.view').forEach(x=>x.classList.toggle('active',x.id===b.dataset.v));document.querySelectorAll('[data-v]').forEach(x=>x.classList.toggle('active',x===b));render()});
 requestForm.onsubmit=e=>{e.preventDefault();d=get();let r=room(d,roomSelect.value),days=dates(start.value,repeat.value,until.value);if(repeat.value!=='one'&&!until.value)return msg('Informe a data final da repetição.');if(+people.value>r.capacity)return msg(`A capacidade desta sala é ${r.capacity} pessoas.`);if(!days.length)return msg('Período de repetição inválido.');let series=days.length>1?id():null;days.forEach(date=>d.requests.push({id:id(),series,owner:me(d).id,room:r.id,date,time:time.value,title:title.value,people:+people.value,notes:notes.value,state:'pending'}));put(d);e.target.reset();start.value=day();msg(`${days.length} solicitação(ões) enviada(s) para aprovação.`);document.querySelector('[data-v="mine"]').click()};
 roomForm.onsubmit=e=>{e.preventDefault();d=get();d.rooms.push({id:id(),name:newRoom.value,floor:newFloor.value,capacity:+newCapacity.value,description:newDescription.value,resources:newResources.value.split(',').map(x=>x.trim()).filter(Boolean)});put(d);e.target.reset();render()};calDate.onchange=render;
 function setState(action,key){d=get();let x=d.requests.find(r=>r.id===key);if(action==='approved'&&d.requests.some(r=>r.id!==key&&r.state==='approved'&&r.room===x.room&&r.date===x.date&&r.time===x.time))return msg('Este horário já foi aprovado para outra solicitação.');x.state=action;put(d);render()}
 function cards(target,items,kind){let e=document.getElementById(target);if(!e)return;e.innerHTML=items.length?items.sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time)).map(x=>{let r=room(get(),x.room),owner=get().users.find(u=>u.id===x.owner);return `<article class="item"><div><strong>${esc(x.title)}</strong> <span class="status ${x.state}">${status(x.state)}</span><p class="muted">${esc(r.name)} · ${br(x.date)} · ${x.time} · ${x.people} pessoas</p><p class="muted">Responsável: ${esc(owner.name)}${x.series?' · Solicitação recorrente':''}</p></div><div class="actions">${kind==='mine'&&['pending','approved'].includes(x.state)?`<button class="secondary" data-cancel="${x.id}">Cancelar</button>`:''}${kind==='approval'?`<button class="primary" data-state="approved" data-id="${x.id}">Aprovar</button><button class="secondary" data-state="rejected" data-id="${x.id}">Recusar</button>`:''}</div></article>`}).join(''):'<div class="card">Nada para mostrar.</div>';e.querySelectorAll('[data-cancel]').forEach(b=>b.onclick=()=>setState('cancelled',b.dataset.cancel));e.querySelectorAll('[data-state]').forEach(b=>b.onclick=()=>setState(b.dataset.state,b.dataset.id))}
 function render(){d=get();cards('mineList',d.requests.filter(x=>x.owner===me(d).id),'mine');let pending=d.requests.filter(x=>x.state==='pending'&&canManage(d,x));cards('approvalList',pending,'approval');const pendingEl=document.getElementById('pending');pendingEl.textContent=pending.length?`(${pending.length})`:'';renderCalendar();renderSetup()}
 function renderCalendar(){let e=document.getElementById('schedule');if(!e)return;d=get();let q=d.requests.filter(x=>x.date===calDate.value&&x.state==='approved');e.innerHTML=`<div class="schedule" style="--n:${d.rooms.length}"><div class="head">Horário</div>${d.rooms.map(r=>`<div class="head">${esc(r.name)}<br><small>${esc(r.floor)}</small></div>`).join('')}${HOURS.map(h=>`<div class="head">${h}</div>${d.rooms.map(r=>{let x=q.find(z=>z.room===r.id&&z.time===h);return `<div class="slot ${x?'busy':''}">${x?`<strong>${esc(x.title)}</strong><br><small>${esc(d.users.find(u=>u.id===x.owner).name)}</small>`:'Livre'}</div>`}).join('')}`).join('')}</div>`}
 function renderSetup(){if(!document.getElementById('rooms'))return;d=get();rooms.innerHTML=d.rooms.map(r=>`<article class="item"><div><strong>${esc(r.name)}</strong><p class="muted">${esc(r.floor)} · ${r.capacity} lugares · ${esc(r.description)}</p><p class="muted">${r.resources.map(esc).join(' · ')||'Sem recursos'}</p></div></article>`).join('');users.innerHTML=d.users.map(u=>`<article class="item"><div><strong>${esc(u.name)}</strong><p class="muted">${u.role} · ${u.active?'ativo':'desativado'}${u.role==='manager'?` · setores: ${u.areas.join(', ')}`:''}</p></div>${u.id!==me(d).id?`<div class="actions"><button class="secondary" data-user="${u.id}">${u.active?'Desativar':'Ativar'}</button>${u.role==='manager'?`<button class="secondary" data-delegate="${u.id}">Delegar setores</button>`:''}</div>`:''}</article>`).join('');document.querySelectorAll('[data-user]').forEach(b=>b.onclick=()=>{d=get();let u=d.users.find(x=>x.id===b.dataset.user);u.active=!u.active;put(d);render()});document.querySelectorAll('[data-delegate]').forEach(b=>b.onclick=()=>{d=get();let u=d.users.find(x=>x.id===b.dataset.delegate),v=prompt('Setores/blocos separados por vírgula:',u.areas.join(', '));if(v!==null){u.areas=v.split(',').map(x=>x.trim()).filter(Boolean);put(d);render()}})}render()}
function publicPanel(){const board=document.getElementById('board');if(!board)return;function go(){let d=get(),h=new Date().getHours(),shift=h<12?'Manhã':h<18?'Tarde':'Noite',range=h<12?[8,12]:h<18?[13,18]:[19,24],items=d.requests.filter(x=>x.state==='approved'&&x.date===day()&&+x.time.slice(0,2)>=range[0]&&+x.time.slice(0,2)<range[1]),g={};items.forEach(x=>{let r=room(d,x.room);(g[r.floor]??=[]).push([r,x])});document.getElementById('shift').textContent=`Programação de hoje · ${shift}`;board.innerHTML=Object.keys(g).length?Object.entries(g).map(([floor,list])=>`<section class="floor"><h2>${esc(floor)}</h2>${list.map(([r,x])=>`<div class="activity"><strong>${esc(r.name)} · ${esc(x.title)}</strong><div class="muted">${esc(d.users.find(u=>u.id===x.owner).name)} · ${x.time}</div></div>`).join('')}</section>`).join(''):'<p>Nenhuma atividade aprovada neste turno.</p>'}function clock(){document.getElementById('clock').textContent=new Date().toLocaleString('pt-BR',{dateStyle:'full',timeStyle:'short'})}go();clock();setInterval(clock,1000)}management();publicPanel();
